# Generated by Django 3.2.15 on 2022-10-15 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('share_currency', models.CharField(max_length=3, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('initial_share_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('initial_share_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('latest_share_price', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('latest_share_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('latest_gain_loss', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
