# Generated by Django 3.2.15 on 2022-10-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_initial_share_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['ticker']},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='initial_share_value',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='latest_gain_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='latest_share_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='latest_share_value',
        ),
    ]
