# Generated by Django 3.2.15 on 2022-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20221016_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='initial_share_value',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='latest_gain_loss',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='latest_share_price',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='latest_share_value',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
