# Generated by Django 3.2.15 on 2022-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20221016_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='initial_share_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='latest_gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='latest_share_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
