# Generated by Django 3.2.15 on 2022-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20221016_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='initial_share_value',
            field=models.FloatField(null=True),
        ),
    ]
