# Generated by Django 3.2.15 on 2022-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_alter_trade_initial_share_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='latest_gain_loss',
            field=models.FloatField(null=True),
        ),
    ]
