# Generated by Django 3.2.15 on 2022-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_alter_trade_latest_gain_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='initial_share_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='latest_gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
