# Generated by Django 3.2.15 on 2022-10-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20221016_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
