# Generated by Django 3.2.15 on 2022-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_remove_trade_latest_gain_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='latest_gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
