# Generated by Django 3.2.15 on 2022-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_remove_trade_initial_share_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='initial_share_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=15),
            preserve_default=False,
        ),
    ]
