# Generated by Django 3.2.15 on 2022-10-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_auto_20221018_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='latest_share_value',
        ),
    ]
