# Generated by Django 3.2.15 on 2022-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_remove_trade_latest_share_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='latest_share_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
