# Generated by Django 3.2.15 on 2022-10-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0017_trade_latest_share_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='latest_share_value',
        ),
    ]
